### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Alterak** [kirill2400/peertube-plugin-download-video-switcher#1]
![Screenshot_1](https://user-images.githubusercontent.com/11453567/135605388-d68ed515-5f3b-46d0-b426-9f9448ae4d39.png)

```
error[01.10.2021, 13:24:43] Cannot remove plugin peertube-plugin-setdefaultvideodownload after failed installation.
{
  "err": {
    "stack": "Error: Invalid NPM plugin name to install\n    at checkNpmPluginNameOrThrow (/var/www/peertube/versions/peertube-nightly-2021-10-01/dist/server/lib/plugins/yarn.js:57:15)\n    at Object.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-01/dist/server/lib/plugins/yarn.js:34:9)\n    at Generator.next (<anonymous>)\n    at /var/www/peertube/versions/peertube-nightly-2021-10-01/node_modules/tslib/tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (/var/www/peertube/versions/peertube-nightly-2021-10-01/node_modules/tslib/tslib.js:113:16)\n    at Object.removeNpmPlugin (/var/www/peertube/versions/peertube-nightly-2021-10-01/dist/server/lib/plugins/yarn.js:33:20)\n    at PluginManager.<anonymous> (/var/www/peertube/versions/peertube-nightly-2021-10-01/dist/server/lib/plugins/plugin-manager.js:233:38)\n    at Generator.throw (<anonymous>)\n    at rejected (/var/www/peertube/versions/peertube-nightly-2021-10-01/node_modules/tslib/tslib.js:115:69)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "message": "Invalid NPM plugin name to install"
  }
}
warn[01.10.2021, 13:24:43] Cannot install plugin peertube-plugin-setdefaultvideodownload.
{
  "err": {
    "err": {
      "stack": "Error: Command failed: yarn add peertube-plugin-setdefaultvideodownload@0.0.4\nwarning package.json: No license field\nwarning No license field\nerror Received malformed response from registry for \"peertube-plugin-setdefaultvideodownload\". The registry may be down.\n\n    at ChildProcess.exithandler (child_process.js:390:12)\n    at ChildProcess.emit (events.js:400:28)\n    at ChildProcess.emit (domain.js:470:12)\n    at maybeClose (internal/child_process.js:1055:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)",
      "message": "Command failed: yarn add peertube-plugin-setdefaultvideodownload@0.0.4\nwarning package.json: No license field\nwarning No license field\nerror Received malformed response from registry for \"peertube-plugin-setdefaultvideodownload\". The registry may be down.\n",
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "yarn add peertube-plugin-setdefaultvideodownload@0.0.4"
    },
    "stdout": "yarn add v1.22.5\ninfo No lockfile found.\n[1/4] Resolving packages...\ninfo Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.\n",
    "stderr": "warning package.json: No license field\nwarning No license field\nerror Received malformed response from registry for \"peertube-plugin-setdefaultvideodownload\". The registry may be down.\n"
  }
}
```

**Comment by kirill2400** [comment]
Plugin have another name

![image](https://user-images.githubusercontent.com/30482699/135611256-c7f03911-d233-4180-8487-cf5d950b344d.png)

**Comment by kirill2400** [comment]
While my plugin not in peertube plugins registry you should use cli tools to install:

sudo -u peertube NODE_CONFIG_DIR=/var/www/peertube/config NODE_ENV=production npm run plugin:install -- --npm-name peertube-plugin-denydownload
